name: Download

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    



    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
          sudo apt install curl
          mkdir acer
            cd acer
          curl https://drive.google.com/uc?id=18sO3p23Tnaso7Ij9YLC40en1ROOv9GWs&amp;confirm=t&amp;uuid=100dc5c9-debd-496c-9bc1-22f917187fc7
   
             
       - name: Release Rom
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: Rom
          name: Rom
          files: | 
            acer/AcerOne_8_T482L(2).zip
